server:
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/xml, text/plain

spring:
  thymeleaf:
    cache: true

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    #driver-class-name:  org.h2.Driver
    #url:                jdbc:h2:file:${application.data.file}
    driver-class-name:  net.sf.log4jdbc.DriverSpy
    url:                jdbc:log4jdbc:h2:file:${application.data.file}
    username:           sa
    password:

security:
  basic:
    enabled: false

application:
  metrics:
    default:
      extract-regex: ".*src/(?:main)/(?:java|groovy)/(.+)\\..+"
      extensions: ".java, .groovy"
      filter: ".*"
    git:
      comment-regex: ".*(Fix|Bug).*"
  chart:
    xaxis: "Refactoring cost"
    yaxis: "Service impact"

  data:
    file: ./whisker.datastore
