CREATE TABLE REPOSITORY (
  REPO_ID     VARCHAR(64)   NOT NULL,
  REPO_NAME   VARCHAR(64)   NOT NULL,
  GIT_DIR     VARCHAR(1024) NOT NULL,
  GIT_REGX    VARCHAR(1024),
  CLS_DIR     VARCHAR(1024) NOT NULL,
  CLS_REGX    VARCHAR(1024),
  SRC_DIR     VARCHAR(1024) NOT NULL,
  SRC_REGX    VARCHAR(1024),
  EXTENSIONS  VARCHAR(64)   NOT NULL,
  MODIFIER    VARCHAR(64)   NOT NULL,
  MODIFIED    DATETIME      NOT NULL,
  PRIMARY KEY(REPO_ID)
);
